[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "3.0.1"
rocket = { version = "0.5.1", features = ["json"] }
rocket_db_pools = { version = "0.2.0", features = ["mongodb"] }
serde_json = "1.0.120"
