[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.188" }
futures = "0.3.21"
tokio = { version = "1.17.0", features = ["full"] }

[dependencies.mongodb]
version = "2.8.2"
features = ["tokio-runtime"]
